export const SIGNIN_CHANGE_LOGIN = 'SIGNIN_CHANGE_LOGIN';
export const SIGNIN_CHANGE_PASSWORD = 'SIGNIN_CHANGE_PASSWORD';

export const SIGNUP_CHANGE_LOGIN = 'SIGNUP_CHANGE_LOGIN';
export const SIGNUP_CHANGE_PASSWORD = 'SIGNUP_CHANGE_PASSWORD';
export const SIGNUP_CHANGE_REPEAT_PASSWORD = 'SIGNUP_CHANGE_REPEAT_PASSWORD';